name: 배포

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: 캐시 복원
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 의존성 설치
      run: |
        cd backend
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install zappa
    - name: AWS 자격 증명 구성
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Zappa 배포
      run: |
        cd backend
        source .venv/bin/activate
        zappa update dev || zappa deploy dev

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: 캐시 복원
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: 의존성 설치 및 빌드
      run: |
        cd frontend
        npm ci
        npm run build
    - name: AWS 자격 증명 구성
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: S3에 배포
      run: |
        aws s3 sync frontend/build s3://simple-react-taekkim --delete